PBLExchangeDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView 

urlpatterns = [
    url(r'^stud/', RedirectView.as_view(url='http://stud.pblexchange.aau.dk/')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^pble_questions/', include('pble_questions.urls', namespace='pble_questions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_users/', include('pble_users.urls', namespace='pble_users'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_subscriptions/', include('pble_subscriptions.urls', namespace='pble_subscriptions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^', include('pblexchange.urls')),
]

pble_questions/urls.py
from django.conf.urls import url, include
from . import views
from .models import Answer, Comment, AnswerVote, CommentVote
from .forms import AnswerForm, CommentForm


urlpatterns = [
    url(r'^search', views.search, name='search'),
    url(r'^new$', views.new, name='new'),
    url(r'^unanswered$', views.unanswered, name='unanswered'),
    url(r'^hot$', views.hot, name='hot'),
    url(r'^bounties$', views.bounties, name='bounties'),
    url(r'^detail/(?P<question_id>[0-9]+)$', views.detail, name='detail'),
    url(r'^tags$', views.tags, name='tags'),
    url(r'^tags/(?P<tag_text>[a-zA-Z0-9_\-]+)$', views.tag, name='tag'),
    url(r'^categories$', views.categories, name='categories'),
    url(r'^categories/(?P<category_id>[0-9]+)$', views.category, name='category'),
    url(r'^ask', views.ask, name='ask'),
    url(r'^submit$', views.submit, name='submit'),
    url(r'^edit/(?P<post_type>[a-z]+)/(?P<post_id>[0-9]+)$', views.edit, name='edit'),
    url(r'^edit_submit/(?P<post_type>[a-z]+)/(?P<post_id>[0-9]+)$', views.edit_submit, name='edit_submit'),
    url(r'^upvote/(?P<post_id>[0-9]+)$', views.vote, {'amount': 1}, name='upvote'),
    url(r'^downvote/(?P<post_id>[0-9]+)$', views.vote, {'amount': -1}, name='downvote'),

    # Post types
    url(r'^answers/', include('pble_questions.answer_urls', namespace='answers'), {
        'post_type': Answer,
        'form_type': AnswerForm,
        'vote_type': AnswerVote,
    }),
    url(r'^comments/', include('pble_questions.comment_urls', namespace='comments'), {
        'post_type': Comment,
        'form_type': CommentForm,
        'vote_type': CommentVote,
    })
]

pble_users/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from . import views
from pble_questions.models import Question, Post
from PBLExchangeDjango.settings import PBLE_GROUPS


detail_patterns = [
    url(r'^$', views.detail, name='detail'),
    url(r'^pble_questions$', views.question_list, {
        'questions': Question.objects.by_user,
        'title_prefix': _('Questions by '),
    }, name='pble_questions'),
    url(r'^unanswered$', views.question_list, {
        'questions': Question.objects.unanswered_by_user,
        'title_prefix': _('Unanswered questions by '),
    }, name='unanswered'),
    url(r'^answers$', views.question_list, {
        'questions': Question.objects.answered_by_user,
        'title_prefix': _('Answers by '),
    }, name='answered'),
    url(r'^bonus_points$', views.bonus_points, name='bonus_points')
]


urlpatterns = [
    url(r'^$', views.users, name='overview'),
    url(r'^detail/(?P<user_id>[0-9]+)/', include(detail_patterns)),
    url(r'^language/(?P<lang_code>[a-zA-Z\-]+)$', views.set_language, name='set_language'),
]

templates/questions/answer_list.html
{% load questions %}
{% load users %}
{% load i18n %}
{% if answers %}
    {% for answer in answers %}
        <div class="pble-a-list-item hentry answer {{ answer.accepted|yesno:"answer-selected pble-a-list-item-selected," }}">
            {% voting answer %}
            <div class="pble-a-item-main">
                {% if answer.question.author.pk == user.pk and not accepted %}
                    <div class="pble-a-selection">
                        <a href="{% url 'pble_questions:answers:accept' answer.pk %}"><input type="submit" value="" title="{% trans 'Click to select as best answer' %}" class="pble-a-select-button"></a>
                    </div>
                {% elif answer.accepted %}
                    <div class="pble-a-selection">
                        <a href="{% url 'pble_questions:answers:accept' answer.pk %}">
                            <input type="submit" value="" class="pble-a-unselect-button" title="{% trans 'Best answer' %}">
                            <div class="pble-a-selected-text">{% trans 'Best answer' %}</div>
                        </a>
                    </div>
                {% endif %}
                <div class="pble-a-item-content">
                    <div class="entry-content">{{ answer.body|safe }}</div>
                </div>
                {% post_meta answer 'pble-a-item' %}

                {% if answer.comment_set.count %}
                <div class="pble-a-item-c-list">
                    {% comment_list answer.question answer %}
                </div>
                {% endif %}

                <div class="pble-a-item-buttons">
                    {% if user == answer.author %}
                    <a href="{% url 'pble_questions:edit' 'answer' answer.pk %}" class="pble-form-light-button pble-form-light-button-edit" style="text-decoration: none; color: inherit;">{% trans 'Edit' %}</a>
                    {% endif %}
                    <label for="comment-a-{{ answer.pk }}" class="pble-form-light-button pble-form-light-button-comment">{% trans 'Add comment' %}</label>
                    <input type="checkbox" id="comment-a-{{ answer.pk }}" class="add-comment">
                    <div class="comment-form pble-c-form" {# style="display: none;" #}>
                        <h2>{% trans 'Your comment on this answer' %}:</h2>
                        <form action="{% url 'pble_questions:comments:submit:a' question.pk answer.pk %}" method="post" class="pure-form pure-form-stacked">
                            {% csrf_token %}
                            {{ comment_form.media }}
                            {{ comment_form }}
                            <br/>
                            <button type="submit" class="pure-button pure-button-primary">{% trans 'Submit' %}</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="pble-a-item-clear"></div>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans 'There are currently no answers' %}.</p>
{% endif %}

templates/questions/categories_list.html
{% load i18n %}
{% load questions %}
{% if categories %}
<div class="pble-nav-cat">
    <div class="pble-nav-cat-list pble-nav-cat-list-1">
        <ul>
        <li class="pble-nav-cat-item pble-nav-cat-all">{% trans 'All categories' %}:</li>

        {% for category in categories %}
            <li class="pble-nav-cat-item"><a href="{% url 'pble_questions:category' category.id %}">{% get_category_name category %}</a> ({{ category.cardinality }})</li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endif %}

templates/questions/comment_list.html
{% load questions %}
{% load i18n %}
{% if comments %}
    {% for comment in comments %}
        <div class="pble-c-list-item hentry comment">
            <div class="pble-c-item-content">
                {{ comment.body|safe }}
            </div>
            <div class="pble-c-item-footer">
                {% post_meta comment %}
                <div class="pble-c-item-buttons">
                    {% if user == comment.author %}
                    <a href="{% url 'pble_questions:edit' 'comment' comment.pk %}" class="pble-form-light-button pble-form-light-button-edit" style="text-decoration: none; color: inherit;">{% trans 'Edit' %}</a>
                    {% endif %}
                </div>
            </div>
            <div class="pble-c-item-clear"></div>
        </div>
    {% endfor %}
{% endif %}

templates/questions/featured_category.html
{% load i18n %}
{% load questions %}

{% if featured_cat %}
    <div class="pble-sidebar">
        <h3>
        {% trans 'Featured category' %}:
        <a href="{% url 'pble_questions:category' featured_cat.category.id %}">{% get_category_name featured_cat.category %}</a></h3>

        <p>{{ featured_text|safe }}</p>
    </div>
{% endif %}

templates/questions/meta.html
{% load users %}
{% load utils %}
{% load questions %}
{% load i18n %}

<span class="{{ class_prefix }}-avatar-meta">
    <span class="{{ class_prefix }}-meta">
        <span class="{{ class_prefix }}-what">{{ what }}</span>
        <span class="{{ class_prefix }}-when">
            <span class="{{ class_prefix }}-when-data"><span class="published updated">{{ post.created_date|timesince|upto:',' }}</span></span><span class="{{ class_prefix }}-when-pad"> {% trans 'ago' %}</span>
        </span>
        {% if post.category %}
        <span class="{{ class_prefix }}-where">
            <span class="{{ class_prefix }}-where-pad">{% trans 'in' %} </span><span class="{{ class_prefix }}-where-data"><a href="{% url 'pble_questions:category' post.category.id %}">{% get_category_name post.category %}</a></span>
        </span>
        {% endif %}
        <span class="{{ class_prefix }}-who">
            <span class="{{ class_prefix }}-who-pad">{% trans 'by' %} </span>
            <span class="{{ class_prefix }}-who-data">{% get_user post.author post.anonymous %}</span>
            {% if not post.anonymous %}
            <span class="{{ class_prefix }}-who-points">
                <span class="{{ class_prefix }}-who-points-pad">(</span><span class="{{ class_prefix }}-who-points-data">{{ post.author.userprofile.points }}</span><span class="{{ class_prefix }}-who-points-pad"> {% trans 'points' %})</span>
            </span>
            {% endif %}
        </span>
    </span>
</span>

templates/questions/question_list.html
{% load questions %}
{% load users %}
{% load i18n %}

<div class="pble-q-list">
{% if questions %}
    {% for question in questions %}
        <div class="pble-q-list-item">
            <div class="pble-q-item-stats">
                {% voting question %}
                <span class="pble-a-count">
                    <span class="pble-a-count-data">{{ question.answer_set.count }}</span><span class="pble-a-count-pad"> {% trans 'answers' %}</span>
                </span>
            </div>
            <div class="pble-q-item-main">
                <div class="pble-q-item-title">
                    {% if question.bounty > 0 %}
                    <span class="pble-bounty">
                        +{{ question.bounty }}
                    </span>
                    {% endif %}
                    <a href="{% url 'pble_questions:detail' question.pk %}">{{ question.title }}</a>
                </div>
                {% post_meta question %}
                {% tag_list question %}
            </div>
            <div class="pble-q-item-clear"></div>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans 'No questions at the moment' %}.</p>
{% endif %}
</div>

templates/questions/search_tag.html
{% load widget_tweaks %}
<form method="GET" action="{% url 'pble_questions:search' %}">
    {{ form.q|add_class:"pble-search-field" }}
    {# <input type="text" name="q" value="" class="pble-search-field"> #}
    <input type="submit" value="Search" class="pble-search-button">
</form>

templates/questions/stats.html
{% load i18n %}
<div class="pble-activity-count">
    <p class="pble-activity-count-item">
        <span class="pble-activity-count-data">{{ questions_count }}</span> {% trans 'questions' %}
    </p>
    <p class="pble-activity-count-item">
        <span class="pble-activity-count-data">{{ answers_count }}</span> {% trans 'answers' %}
    </p>
    <p class="pble-activity-count-item">
        <span class="pble-activity-count-data">{{ comments_count }}</span> {% trans 'comments' %}
    </p>
    <p class="pble-activity-count-item">
        <span class="pble-activity-count-data">{{ users_count }}</span> {%trans 'users' %}
    </p>
</div>

templates/questions/tag_list.html
{% if tags %}
    <div class="{{ class_prefix }}-tags">
        <ul class="{{ class_prefix }}-tag-list">
            {% for tag in tags %}
                <li class="{{ class_prefix }}-tag-item"><a href="{% url 'pble_questions:tag' tag.tag %}" class="pble-tag-link">{{ tag.tag }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/questions/top_challenges.html
{% load i18n %}

{% if top_challenges %}
    <div class="pble-sidebar">
        <div class="pble-nav-cat-list pble-nav-cat-list-1">
            <ul>
                <li class="pble-nav-cat-item pble-nav-cat-all">{% trans 'Newest challenges' %}:</li>

            {% for challenge_q in top_challenges %}
                <li class="pble-nav-cat-item"><a href="{% url 'pble_questions:detail' challenge_q.id %}">{{ challenge_q.title }}</a>
                    <span class="pble-bounty">
                        +{{ challenge_q.bounty }}
                    </span>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
{% endif %}

templates/questions/vote.html
{% load i18n %}
<div class="pble-voting pble-voting-net">
    <div class="pble-vote-buttons pble-vote-buttons-net">
        <a href="{% url post_upvote post.pk %}" title="{% trans 'Click to vote up' %}" class="pble-vote-first-button pble-vote-up-button">+</a>
        <a href="{% url post_downvote post.pk %}" title="{% trans 'Click to vote down' %}" class="pble-vote-second-button pble-vote-down-button">-</a>
    </div>
    <div class="pble-vote-count pble-vote-count-net">
        <span class="pble-netvote-count">
            <span class="pble-netvote-count-data">{{ post.votes }}</span><span class="pble-netvote-count-pad"> {% trans 'votes' %}</span>
        </span>
    </div>
    <div class="pble-vote-clear"></div>
</div>