PBLExchangeDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView 

urlpatterns = [
    url(r'^stud/', RedirectView.as_view(url='http://stud.pblexchange.aau.dk/')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^pble_questions/', include('pble_questions.urls', namespace='pble_questions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_users/', include('pble_users.urls', namespace='pble_users'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_subscriptions/', include('pble_subscriptions.urls', namespace='pble_subscriptions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^', include('pblexchange.urls')),
]

pble_users/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from . import views
from pble_questions.models import Question, Post
from PBLExchangeDjango.settings import PBLE_GROUPS


detail_patterns = [
    url(r'^$', views.detail, name='detail'),
    url(r'^pble_questions$', views.question_list, {
        'questions': Question.objects.by_user,
        'title_prefix': _('Questions by '),
    }, name='pble_questions'),
    url(r'^unanswered$', views.question_list, {
        'questions': Question.objects.unanswered_by_user,
        'title_prefix': _('Unanswered questions by '),
    }, name='unanswered'),
    url(r'^answers$', views.question_list, {
        'questions': Question.objects.answered_by_user,
        'title_prefix': _('Answers by '),
    }, name='answered'),
    url(r'^bonus_points$', views.bonus_points, name='bonus_points')
]


urlpatterns = [
    url(r'^$', views.users, name='overview'),
    url(r'^detail/(?P<user_id>[0-9]+)/', include(detail_patterns)),
    url(r'^language/(?P<lang_code>[a-zA-Z\-]+)$', views.set_language, name='set_language'),
]

pble_users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import Group

from django.core.validators import MinValueValidator

from PBLExchangeDjango import settings


# Create your models here.
class UserProfileManager(models.Manager):
    def sorted_score_descending(self):
        return self.all().order_by('-points')


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    points = models.PositiveIntegerField(default=1)
    challenge_points = models.PositiveIntegerField(default=0)
    title = models.CharField(max_length=32, default=settings.PBLE_GROUPS[0][0])  # By default join "lowest" user group

    objects = UserProfileManager()

    def save(self, *args, **kw):
        old = type(self).objects.get(pk=self.pk) if self.pk else None
        if old and old.points != self.points:
            for k, v in reversed(settings.PBLE_GROUPS):
                if self.points >= v:
                    self.user.groups.clear()  # TODO: should the user belong to one or multiple groups?
                    k_group, c = Group.objects.get_or_create(name=k)
                    k_group.user_set.add(self.user)
                    self.title = k
                    break
        super(UserProfile, self).save(*args, **kw)


class UserSetting(models.Model):
    user = models.OneToOneField(User, unique=True)
    post_notification_enabled = models.BooleanField(default=True)
    subscription_enabled = models.BooleanField(default=True)
    language = models.CharField(verbose_name=_('language'), max_length=5, choices=settings.LANGUAGES, default=settings.LANGUAGE_CODE)

pble_users/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import UserProfile


class BonusPointForm(forms.ModelForm):
    error_css_class = 'error'
#    points = forms.IntegerField(
#        validators=[MinValueValidator(1), MaxValueValidator(500)]
#    )

    class Meta:
        model = UserProfile
        fields = [
            'points',
            'challenge_points'
        ]

pble_users/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, HttpResponseRedirect, Http404, HttpResponse, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.utils.translation import check_for_language

from pble_users import models
from pble_users.forms import BonusPointForm
from pblexchange.models import ExternalLink
from PBLExchangeDjango import settings
from .decorators import group_required


# Create your views here.
def users(request, base_template='pblexchange/base.html', **kwargs):
    return render(request, 'users/user_list.html', {
        'base_template': base_template,
        'userprofiles': models.UserProfile.objects.sorted_score_descending(),
        'link_list': ExternalLink.objects.filter(featured=True), 
    })


def detail(request, user_id, base_template='pblexchange/base.html', **kwargs):
    user_profile = models.UserProfile.objects.get(user=User.objects.get(id=user_id))
    return render(request, 'users/detail.html', {
        'base_template': base_template,
        'user_profile': user_profile
    })


def question_list(request, user_id, questions, title_prefix='', base_template='pblexchange/base.html', **kwargs):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'users/user_questions.html', {
        'base_template': base_template,
        'user_profile': user.userprofile,
        'title': title_prefix + user.get_full_name(),
        'questions': questions(user),
        'link_list': ExternalLink.objects.filter(featured=True),
    })


@group_required()  # Leave blank to only allow admins
def bonus_points(request, user_id, **kwargs):
    if request.method == 'POST' and request.user.is_authenticated() and request.user.is_superuser:
        form = BonusPointForm(request.POST)
        if 'pble_users' in settings.INSTALLED_APPS:
            if form.is_valid():
                target_profile = get_object_or_404(User, pk=user_id).userprofile
                target_profile.points += form.cleaned_data['points']
                target_profile.challenge_points += form.cleaned_data['challenge_points']
                target_profile.save()

                return HttpResponseRedirect(reverse('pble_users:detail', args=(target_profile.user_id,)))
            else:  # TODO: Better error handling
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            raise Http404("'pble_users' module does not exist under INSTALLED_APPS in settings.py")  # TODO: display a proper error message
    else:
        raise Http404()


def set_language(request, lang_code, **kwargs):
    if request.user.is_authenticated():
        if lang_code and check_for_language(lang_code):
            request.user.usersetting.language = lang_code
            request.user.usersetting.save()
    redirect = request.META.get('HTTP_REFERER')
    if not redirect:
        redirect = reverse('home')
    return HttpResponseRedirect(redirect)

pble_users/templates/users/detail.html
{% extends 'users/user_questions.html' %}
{% load users %}
{% load i18n %}

{% block sidepanel %}
{% endblock %}

{% block content %}
    <h1>{% trans 'User' %} {{ user_profile.user.get_full_name }} ({{ user_profile.user.username }})</h1>
    <div class="pble-part-form-activity">
        <h2>{% trans 'Activity by' %} {{ user_profile.user.get_full_name }}</h2>
        {# TODO: Display error msg when validator fails #}
        <form action="{% url 'pble_users:bonus_points' user_profile.user_id %}" method="post">
            {% csrf_token %}
            <table class="pble-form-wide-table">
                <tbody>
                    {% if user.is_authenticated and user.is_superuser %}
                        <tr id="bonus">
                            <td class="pble-form-wide-label">{% trans 'Bonus points' %}:</td>
                            <td class="pble-form-wide-data">
                                <input class="pble-form-wide-number" name="points" value="0" type="number" min="0" required id="id_points" />
                                <span class="pble-form-wide-note">({% trans 'only shown to admins' %})</span>
                            </td>
                        </tr>
                        <tr id="challenge">
                            <td class="pble-form-wide-label">{% trans 'Add challenge points' %}:</td>
                            <td class="pble-form-wide-data">
                                <input class="pble-form-wide-number" name="challenge_points" value="0" type="number" min="0" required id="id_challenge_points" />
                                <span class="pble-form-wide-note">({% trans 'only shown to admins' %})</span>
                            </td>
                        </tr>
                    {% endif %}
                    <tr id="points">
                        <td class="pble-form-wide-label">{% trans 'Score' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-points">{{ user_profile.points }}</span>
                                {% trans 'points' %} ({% trans 'ranked' %} #
                                <span class="pble-uf-user-rank">{{ user_profile|get_rank:user_profile.points }}</span>)
                            </span>
                        </td>
                    </tr>
                    {% if user_profile.challenge_points > 0 %}
                    <tr id="challenge_points">
                        <td class="pble-form-wide-label">{% trans 'Challenge points' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-points">{{ user_profile.challenge_points }}</span>
                                {% trans 'points' %}
                            </span>
                        </td>
                    </tr>
                    {% endif %}
                    <tr id="title">
                        <td class="pble-form-wide-label">{% trans 'Title' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">{{ user_profile.title }}</span>
                        </td>
                    </tr>
                    <tr id="questions">
                        <td class="pble-form-wide-label">{% trans 'Questions'%}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-q-posts">{% user_questions_quantity user_profile.user %}</span>
                                (<span class="pble-uf-user-q-selecteds">{% user_accepted_answers user_profile.user %}</span>
                                {% trans 'with best answer chosen' %})
                            </span>
                        </td>
                    </tr>
                    <tr id="answers">
                        <td class="pble-form-wide-label">{% trans 'Answers' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-a-posts">{% user_answers user_profile.user %}</span>
                                (<span class="pble-uf-user-a-selecteds">{% user_answers_chosen user_profile.user %}</span>
                                {% trans 'chosen as best' %})
                            </span>
                        </td>
                    </tr>
                    <tr id="comments">
                        <td class="pble-form-wide-label">{% trans 'Comments' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-c-posts">{% user_comments_quantity user_profile.user %}</span>
                            </span>
                        </td>
                    </tr>
                    <tr id="votedon">
                        <td class="pble-form-wide-label">{% trans 'Voted on' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-q-votes">{% user_question_votes user_profile.user %}</span>
                                {% trans 'questions' %},
                                <span class="pble-uf-user-a-votes">{% user_answer_votes user_profile.user %}</span>
                                {% trans 'answers' %}
                            </span>
                        </td>
                    </tr>
                    <tr id="votegave">
                        <td class="pble-form-wide-label">{% trans 'Gave out' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-upvotes">{% user_upvotes_given user_profile.user %}</span>
                                {% trans 'up votes' %},
                                <span class="pble-uf-user-downvotes">{% user_downvotes_given user_profile.user %}</span>
                                {% trans 'down votes' %}
                            </span>
                        </td>
                    </tr>
                    <tr id="votegot">
                        <td class="pble-form-wide-label">{% trans 'Received' %}:</td>
                        <td class="pble-form-wide-data">
                            <span class="pble-form-wide-static">
                                <span class="pble-uf-user-upvotes">{% user_upvotes_received user_profile.user %}</span>
                                {% trans 'up votes' %},
                                <span class="pble-uf-user-downvotes">{% user_downvotes_received user_profile.user %}</span>
                                {% trans 'down votes' %}
                            </span>
                        </td>
                    </tr>
                    {% if user.is_authenticated and user.is_superuser %}
                        <tr>
                            <td class="pble-form-wide-buttons" colspan="3">
                                <input class="pble-form-wide-button pble-form-wide-button-setbonus" name="bonus_points_btn" value="{% trans 'Update bonus' %}" title="" type="submit">
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </form>
    </div>
{% endblock %}

pble_users/templates/users/user_list.html
{% extends base_template %}
{% load users %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Top scoring users' %}</h1>
    <div class="pble-part-ranking">
        {% if userprofiles %}
            {% for userprofile in userprofiles %}
                <span class="pble-ranking-item pble-top-users-item">
                    <span class="pble-top-users-label">{% userprofile_get_user userprofile %}</span>
                    <span class="pble-top-users-score">{{ userprofile.points }}</span>
                </span>
            {% endfor %}
        {% else %}
            <p>{% trans 'No registered user(s) at the moment' %}.</p>
        {% endif %}
    </div>
{% endblock %}

pble_users/templates/users/user_questions.html
{% extends base_template %}
{% load questions %}
{% load i18n %}

{% block sub_menu %}
    <ul class="pble-nav-sub-list">
        <li class="pble-nav-sub-item"><a href="{% url 'pble_users:detail' user_profile.user_id %}" class="pble-nav-sub-link">{% trans 'User' %} {{ user_profile.user.username }}</a></li>
        <li class="pble-nav-sub-item"><a href="{% url 'pble_users:pble_questions' user_profile.user_id %}" class="pble-nav-sub-link">{% trans 'Questions' %}</a></li>
        <li class="pble-nav-sub-item"><a href="{% url 'pble_users:unanswered' user_profile.user_id %}" class="pble-nav-sub-link">{% trans 'Unanswered' %}</a></li>
        <li class="pble-nav-sub-item"><a href="{% url 'pble_users:answered' user_profile.user_id %}" class="pble-nav-sub-link">{% trans 'Answers' %}</a></li>
    </ul>
{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    {% question_list questions %}
{% endblock %}