PBLExchangeDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView 

urlpatterns = [
    url(r'^stud/', RedirectView.as_view(url='http://stud.pblexchange.aau.dk/')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^pble_questions/', include('pble_questions.urls', namespace='pble_questions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_users/', include('pble_users.urls', namespace='pble_users'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_subscriptions/', include('pble_subscriptions.urls', namespace='pble_subscriptions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^', include('pblexchange.urls')),
]

pble_subscriptions/urls.py
from django.conf.urls import url, include
from . import views

subscribe_patterns = [
    url(r'category/(?P<category_id>[0-9]+)$', views.alter_categories, name='subscribe_category'),
    url(r'tag/(?P<tag_id>[0-9]+)$', views.alter_tags, name='subscribe_tag'),
    url(r'peer/(?P<userid>[0-9]+)$', views.alter_peers, name='subscribe_peer')
]

urlpatterns = [
    url(r'^categories$', views.categories, name='categories'),
    url(r'^tags$', views.tags, name='tags'),
    url(r'^peers$', views.peers, name='peers'),
    url(r'^alter_subscription/', include(subscribe_patterns)),
    url(r'^alter_subscription_settings', views.alter_subscription_settings, name='alter_subscription_settings'),
]

pble_users/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from . import views
from pble_questions.models import Question, Post
from PBLExchangeDjango.settings import PBLE_GROUPS


detail_patterns = [
    url(r'^$', views.detail, name='detail'),
    url(r'^pble_questions$', views.question_list, {
        'questions': Question.objects.by_user,
        'title_prefix': _('Questions by '),
    }, name='pble_questions'),
    url(r'^unanswered$', views.question_list, {
        'questions': Question.objects.unanswered_by_user,
        'title_prefix': _('Unanswered questions by '),
    }, name='unanswered'),
    url(r'^answers$', views.question_list, {
        'questions': Question.objects.answered_by_user,
        'title_prefix': _('Answers by '),
    }, name='answered'),
    url(r'^bonus_points$', views.bonus_points, name='bonus_points')
]


urlpatterns = [
    url(r'^$', views.users, name='overview'),
    url(r'^detail/(?P<user_id>[0-9]+)/', include(detail_patterns)),
    url(r'^language/(?P<lang_code>[a-zA-Z\-]+)$', views.set_language, name='set_language'),
]

pble_subscriptions/models.py
from django.db import models
from django.contrib.auth.models import User
from pble_questions.models import Question
from pble_users.models import UserProfile


# Create your models here.
class Subscription(models.Model):
    NEVER = 'NEVER'
    DAILY = 'DAILY'
    WEEKLY = 'WEEKLY'
    DIGEST_CHOICES = ((NEVER, 'Never'), (DAILY, 'Daily'), (WEEKLY, 'Weekly'))

    user = models.OneToOneField(User, unique=True)
    categories = models.ManyToManyField('pble_questions.Category')
    tags = models.ManyToManyField('pble_questions.Tag')
    peers = models.ManyToManyField(UserProfile)
    answer_notifications = models.BooleanField(default=True)
    comment_notifications = models.BooleanField(default=False)
    digest = models.CharField(max_length=6, choices=DIGEST_CHOICES, default=NEVER)


class Notification(models.Model):
    class Meta:
        abstract = True

    created_date = models.DateTimeField(auto_now_add=True)


class QuestionNotification(Notification):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

pble_subscriptions/forms.py
from django import forms
from .models import Subscription


class SubscriptionSettingsForm(forms.Form):
    answer_check = forms.BooleanField(required=False)
    comment_check = forms.BooleanField(required=False)
    subscription_digest = forms.MultipleChoiceField(choices=Subscription.DIGEST_CHOICES, label="digest choice", required=True)

    class Meta:
        model = Subscription
        fields = [
            'answer_check',
            'comment_check',
            'subscription_digest'
        ]

pble_subscriptions/views.py
import os
import sys

from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404, Http404
from django.contrib.auth.models import User
from .models import Subscription
from .forms import SubscriptionSettingsForm
from pble_questions.models import Category, Tag
from pble_users.models import UserProfile
from pble_questions.models import Question, Answer, Comment
from django.core.mail import send_mail, get_connection, EmailMultiAlternatives
from django.template import loader
from django.contrib.sites.models import Site


# Create your views here.
def categories(request, base_template='pblexchange/base.html', error_message='', **kwargs):
    if not request.user.is_authenticated():
        HttpResponseRedirect(reverse('login'))

    lang = request.user.usersetting.language[:2]
    user_sub, _ = Subscription.objects.get_or_create(user=request.user)
    user_category_subs = user_sub.categories.order_by(lang + '_name')
    user_category_nonsubs = Category.objects.all().exclude(en_name__in=list(user_category_subs)).order_by(lang + '_name')
    answer_notifications = user_sub.answer_notifications
    comment_notifications = user_sub.comment_notifications
    return render(request, 'subscriptions/category_list.html', {
        'base_template': base_template,
        'sub_categories': user_category_subs,
        'not_sub_categories': user_category_nonsubs,
        'answer_notifications': answer_notifications,
        'comment_notifications': comment_notifications,
        'error_message': error_message,
    })


def tags(request, base_template='pblexchange/base.html', error_message='', **kwargs):
    if not request.user.is_authenticated():
        HttpResponseRedirect(reverse('login'))

    user_sub, _ = Subscription.objects.get_or_create(user=request.user)
    user_tag_subs = user_sub.tags.order_by('tag')
    user_tag_nonsubs = Tag.objects.all().exclude(tag__in=list(user_tag_subs)).order_by('tag')
    answer_notifications = user_sub.answer_notifications
    comment_notifications = user_sub.comment_notifications
    return render(request, 'subscriptions/tag_list.html', {
        'base_template': base_template,
        'sub_tags': user_tag_subs,
        'not_sub_tags': user_tag_nonsubs,
        'answer_notifications': answer_notifications,
        'comment_notifications': comment_notifications,
        'error_message': error_message,
    })


def peers(request, base_template='pblexchange/base.html', error_message='', **kwargs):
    if not request.user.is_authenticated():
        HttpResponseRedirect(reverse('login'))

    user_sub, _ = Subscription.objects.get_or_create(user=request.user)
    user_users_subs = user_sub.peers.order_by('user__username')
    usrs = UserProfile.objects.all().exclude(user=request.user).\
        exclude(user__in=[u.user for u in user_users_subs]).order_by('user__username')
    answer_notifications = user_sub.answer_notifications
    comment_notifications = user_sub.comment_notifications
    return render(request, 'subscriptions/peer_list.html', {
        'base_template': base_template,
        'sub_users': user_users_subs,
        'not_sub_users': usrs,
        'answer_notifications': answer_notifications,
        'comment_notifications': comment_notifications,
        'error_message': error_message,
    })


def alter_categories(request, category_id, **kwargs):
    if not request.user.is_authenticated():
        HttpResponseRedirect(reverse('login'))

    category = get_object_or_404(Category, id=category_id)
    user_sub, _ = Subscription.objects.get_or_create(user=request.user)

    if category in user_sub.categories.all():
        user_sub.categories.remove(category)
    else:
        user_sub.categories.add(category)

    user_sub.save()
    return HttpResponseRedirect(reverse('pble_subscriptions:categories'))


def alter_tags(request, tag_id, **kwargs):
    if not request.user.is_authenticated():
        HttpResponseRedirect(reverse('login'))

    tag = get_object_or_404(Tag, id=tag_id)
    user_sub, _ = Subscription.objects.get_or_create(user=request.user)

    if tag in user_sub.tags.all():
        user_sub.tags.remove(tag)
    else:
        user_sub.tags.add(tag)

    user_sub.save()
    return HttpResponseRedirect(reverse('pble_subscriptions:tags'))


def alter_peers(request, userid, **kwargs):
    if not request.user.is_authenticated():
        HttpResponseRedirect(reverse('login'))

    username_usr = User.objects.get(id=userid)

    if request.user != username_usr:
        username_up = UserProfile.objects.get(user=username_usr)
        request_usr__sub, _ = Subscription.objects.get_or_create(user=request.user)

        if username_up in request_usr__sub.peers.all():
            request_usr__sub.peers.remove(username_up)
        else:
            request_usr__sub.peers.add(username_up)
        request_usr__sub.save()

    return HttpResponseRedirect(reverse('pble_subscriptions:peers'))


def alter_subscription_settings(request, form_type=SubscriptionSettingsForm, **kwargs):
    if not request.user.is_authenticated():
        HttpResponseRedirect(reverse('login'))

    if request.method == 'POST':
        post_form = form_type(request.POST)
        if post_form.is_valid():
            user_subscription = Subscription.objects.get(user=request.user)
            form_data = post_form.cleaned_data
            user_subscription.answer_notifications = form_data.get('answer_check')
            user_subscription.comment_notifications = form_data.get('comment_check')
            user_subscription.digest = form_data.get('subscription_digest')[0]
            user_subscription.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else: # TODO: is there dynamic way to determine referer association?
            if 'categories' in request.META.get('HTTP_REFERER'):
                return categories(request, 'pblexchange/base.html',
                                  error_message='Input error; subscription and notification settings was not changed')
            elif 'tags' in request.META.get('HTTP_REFERER'):
                return tags(request, 'pblexchange/base.html',
                            error_message='Input error; subscription and notification settings was not changed')
            elif 'peers' in request.META.get('HTTP_REFERER'):
                return peers(request, 'pblexchange/base.html',
                             error_message='Input error; subscription and notification settings was not changed')
    else:
        raise Http404


# Notification methods
# TODO: Consider making these functions use celery task methods for asynchronous behaviour
def send_answer_notification(answer, **kwargs):
    a_author_subscription = Subscription.objects.get(user=answer.question.author)
    if a_author_subscription.answer_notifications and answer.author != answer.question.author:
        current_site = Site.objects.get_current()
        q_url = current_site.domain + reverse('pble_questions:detail', args=(
            answer.question.id,))
        if answer.anonymous:
            a_author = 'anonymous'
        else:
            a_author = answer.author.username

        html_message = loader.render_to_string(
            'subscriptions/answer_notification.html',
            {
                'answer_author': a_author,
                'recipient_username': answer.question.author.username,
                'q_url': q_url,
                'answer_text': answer.body,
                'q_title': answer.question.title
            }
        )

        send_mail('PBL Exchange new answer', '', 'pblexchange@aau.dk', [answer.question.author.email],
                  fail_silently=True, html_message=html_message)


def send_comment_notifications(comment):
    receivers_list = set()
    comments = comment.answer.comment_set.filter(author__subscription__comment_notifications=True, answer=comment.answer) if comment.answer \
        else comment.question.comment_set.filter(author__subscription__comment_notifications=True, answer__isnull=True)
    post_author = comment.answer.author if comment.answer else comment.question.author
    current_site = Site.objects.get_current()
    q_url = current_site.domain + reverse('pble_questions:detail', args=(
        comment.question.id,))

    try:
        connection = get_connection()  # uses SMTP server specified in settings.py
        connection.open()  # If you don't open the connection manually, Django will automatically open, then tear down the connection in msg.send()
    except ConnectionRefusedError:
        sys.stderr.write('Could not open connection to SMTP server.')
        return

    for e in comments:
        receivers_list.add(e.author)

    if Subscription.objects.get(user=post_author).comment_notifications:
        receivers_list.add(post_author)

    if comment.anonymous:
        c_author = 'anonymous'
    else:
        c_author = comment.author.username

    for user in receivers_list:
        html_message = loader.render_to_string(
            'subscriptions/comment_notification.html',
            {
                'recipient_username': user.username,
                'q_url': q_url,
                'answer_text': comment.answer.body if comment.answer else '',
                'comment_text': comment.body,
                'q_title': comment.question.title,
                'comment_author': c_author,
            }
        )
        message = EmailMultiAlternatives('PBL Exchange daily digest', '', 'pblexchange@aau.dk', [user.email],
                                         connection=connection)
        message.attach_alternative(html_message, 'text/html')
        message.send()

    connection.close()  # Cleanup

pble_subscriptions/templates/subscriptions/accepted_notification.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2>Hello {{ recipient_username }},</h2>
        <h3>
            {{ question_author }} has {{ accept_action }} your answer to the question <a href="{{ q_url }}">{{ q_title }}</a>
        </h3>
    </body>
</html>

pble_subscriptions/templates/subscriptions/answer_notification.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2>Hello {{ recipient_username }},</h2>
        <h3>
            {{ answer_author }} has provided the following answer to your question <a href="{{ q_url }}">{{ q_title }}</a>
        </h3>
        Answer: {{ answer_text|striptags|safe }}
    </body>
</html>

pble_subscriptions/templates/subscriptions/base.html
{% extends base_template %}
{% load subscriptions %}
{% load i18n %}

{% block sub_menu %}
    <ul class="pble-nav-sub-list">
        <li class="pble-nav-sub-item"><a href="{% url 'pble_subscriptions:categories' %}" class="pble-nav-sub-link">{% trans 'Categories' %}</a></li>
        <li class="pble-nav-sub-item"><a href="{% url 'pble_subscriptions:tags' %}" class="pble-nav-sub-link">{% trans 'Tags' %}</a></li>
        <li class="pble-nav-sub-item"><a href="{% url 'pble_subscriptions:peers' %}" class="pble-nav-sub-link">{% trans 'Peers' %}</a></li>
    </ul>
{% endblock %}

{% block sidepanel %}
    <div class="pble-sidepanel">
        <div class="pble-widgets-side pble-widget-side-top">
            <div class="pble-widget-side pble-widget-side-top">
                <p>{% trans 'Interested in a specific type of content?' %}<br>
                {% trans 'Subscribe or unsubscribe to the categories, tags or peers who pique your interest by clicking on them.' %}</p>
            </div>
        </div>

        <div class="pble-sidebar">
            <form action="{% url 'pble_subscriptions:alter_subscription_settings' %}" method="post">
            {% csrf_token %}
                {% if error_message %}
                    <strong style="color: red;"> {{ error_message }}<br></strong>
                {% endif %}
                {% trans 'Change your notifications settings:' %}<br><br>

                {% if answer_notifications %}
                <input type="checkbox" name="answer_check" value="answer_enabled" checked>{% trans 'Answer notifications' %}<br>
                {% else %}
                <input type="checkbox" name="answer_check" value="answer_enabled">{% trans 'Answer notifications' %}<br>
                {% endif %}

                {% if comment_notifications %}
                <input type="checkbox" name="comment_check" value="comment_enabled" checked>{% trans 'Comment notifications' %}<br>
                {% else %}
                <input type="checkbox" name="comment_check" value="comment_enabled">{% trans 'Comment notifications' %}<br>
                {% endif %}

                <!-- Grouped checkboxes for digest options -->
                <!-- TODO: auto generate the digest options html -->
                {% digest_options user.id %}

                <br><br>
                <input class="pble-form-wide-button pble-form-wide-button-setbonus" name="update_btn" value="{% trans 'Update' %}" title="" type="submit">
            </form>
        </div>
    </div>
{% endblock %}

pble_subscriptions/templates/subscriptions/category_list.html
{% extends 'subscriptions/base.html' %}
{% load i18n %}
{% load questions %}

{% block content %}
    <h1>{% trans 'Categories you are subscribed to:'%}</h1>
    <div class="pble-part-ranking">
    {% for category in sub_categories %}
        <span class="pble-ranking-item pble-top-tags-item">
            <span class="pble-top-tags-label"><a href="{% url 'pble_subscriptions:subscribe_category' category.id %}" class="pble-tag-link">{% get_category_name category %}</a></span>
            <!-- TODO: set proper href to category sub/unsub -->
        </span>
    {% endfor %}
    </div>

    <h1>{% trans 'Categories you are <u>not</u> subscribed to:' %}</h1>
    <div class="pble-part-ranking">
    {% for category in not_sub_categories %}
        <span class="pble-ranking-item pble-top-tags-item">
            <span class="pble-top-tags-label"><a href="{% url 'pble_subscriptions:subscribe_category' category.id %}" class="pble-tag-link">{% get_category_name category %}</a></span>
            <!-- TODO: set proper href to category sub/unsub -->
        </span>
    {% endfor %}
    </div>
{% endblock %}

pble_subscriptions/templates/subscriptions/comment_notification.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2>Hello {{ recipient_username }},</h2>
        <h3>
            {{ comment_author }} has provided the following comment to a question or answer you also commented on:
        </h3>
        Question:  <a href="{{ q_url }}">{{ q_title }}</a><br>

        {% if answer_text %}
        Answer: {{ answer_text|striptags|safe }}<br>
        {% endif %}

        Comment: {{ comment_text|striptags|safe }}
    </body>
</html>

pble_subscriptions/templates/subscriptions/digest_notification.html
{% load subscriptions %}

<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2>Hello {{ recipient }}, this is your {{ digest_option }} digest.</h2>
        {% if category_questions %}
            <h4>
                Questions matching your category subscription
            </h4>

            {% for q in category_questions %}
            {% question_url q %}: {{ q.category }}<br>
            {% endfor %}

            <br>
        {% endif %}
        {% if peer_questions %}
            <h4>
                Questions matching your peer subscription
            </h4>
            {% for q in peer_questions %}
                {% question_url q %}: {% if q.anonymous %} anonymous {% else %} {{ q.author }} {% endif %}<br>
            {% endfor %}
        {% endif %}

            <br>
        {% if tag_questions %}
            <h4>
                Questions matching your tag subscription
            </h4>
            {% for q in tag_questions %}
                {% question_url q %}: {% for t in q.tags.all %} {{ t.tag }}, {% endfor %}<br>
            {% endfor %}
        {% endif %}
    </body>
</html>

pble_subscriptions/templates/subscriptions/digest_options.html
{% load i18n %}

{% if current_digest == "NEVER" %}
    <fieldset class="form-group">
        <legend class="legend-label">{% trans 'Subscription Digest' %}</legend>
        <label class="radio-inline">
            <input id="digest1" name="subscription_digest" value="NEVER" type="radio" checked> {% trans 'Never' %}
        </label>
        <label class="radio-inline">
            <input id="digest2" name="subscription_digest" value="DAILY" type="radio"> {% trans 'Daily' %}
        </label>
        <label class="radio-inline">
            <input id="digest3" name="subscription_digest" value="WEEKLY" type="radio"> {% trans 'Weekly' %}
        </label>
    </fieldset>
{% elif current_digest == "DAILY" %}
    <fieldset class="form-group">
        <legend class="legend-label">{% trans 'Subscription Digest' %}</legend>
        <label class="radio-inline">
            <input id="digest1" name="subscription_digest" value="NEVER" type="radio"> {% trans 'Never' %}
        </label>
        <label class="radio-inline">
            <input id="digest2" name="subscription_digest" value="DAILY" type="radio" checked> {% trans 'Daily' %}
        </label>
        <label class="radio-inline">
            <input id="digest3" name="subscription_digest" value="WEEKLY" type="radio"> {% trans 'Weekly' %}
        </label>
    </fieldset>
{% elif current_digest == "WEEKLY" %}
    <fieldset class="form-group">
        <legend class="legend-label">{% trans 'Subscription Digest' %}</legend>
        <label class="radio-inline">
            <input id="digest1" name="subscription_digest" value="NEVER" type="radio"> {% trans 'Never' %}
        </label>
        <label class="radio-inline">
            <input id="digest2" name="subscription_digest" value="DAILY" type="radio"> {% trans 'Daily' %}
        </label>
        <label class="radio-inline">
            <input id="digest3" name="subscription_digest" value="WEEKLY" type="radio" checked> {% trans 'Weekly' %}
        </label>
    </fieldset>
{% endif %}

pble_subscriptions/templates/subscriptions/peer_list.html
{% extends 'subscriptions/base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Users you are subscribed to:' %}</h1>
    <div class="pble-part-ranking">
    {% for userprofile in sub_users %}
        <span class="pble-ranking-item pble-top-tags-item">
            <span class="pble-top-tags-label"><a href="{% url 'pble_subscriptions:subscribe_peer' userprofile.user.id %}" class="pble-tag-link">{{ userprofile.user.username }}</a></span>
        </span>
    {% endfor %}
    </div>

    <h1>{% trans 'Users you are <u>not</u> subscribed to:' %}</h1>
    <div class="pble-part-ranking">
    {% for userprofile in not_sub_users %}
        <span class="pble-ranking-item pble-top-tags-item">
            <span class="pble-top-tags-label"><a href="{% url 'pble_subscriptions:subscribe_peer' userprofile.user.id %}" class="pble-tag-link">{{ userprofile.user.username }}</a></span>
            <!-- TODO: set proper href to category sub/unsub -->
        </span>
    {% endfor %}
    </div>
{% endblock %}

pble_subscriptions/templates/subscriptions/question_href.html
<a href={{ q_url }}>{{ q_title }}</a>

pble_subscriptions/templates/subscriptions/tag_list.html
{% extends 'subscriptions/base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Tags you are subscribed to:' %}</h1>
    <div class="pble-part-ranking">
    {% for tag in sub_tags %}
        <span class="pble-ranking-item pble-top-tags-item">
            <span class="pble-top-tags-label"><a href="{% url 'pble_subscriptions:subscribe_tag' tag.id %}" class="pble-tag-link">{{ tag.tag }}</a></span>
            <!-- TODO: set proper href to category sub/unsub -->
        </span>
    {% endfor %}
    </div>

    <h1>{% trans 'Tags you are <u>not</u> subscribed to:' %}</h1>
    <div class="pble-part-ranking">
    {% for tag in not_sub_tags %}
        <span class="pble-ranking-item pble-top-tags-item">
            <span class="pble-top-tags-label"><a href="{% url 'pble_subscriptions:subscribe_tag' tag.id %}" class="pble-tag-link">{{ tag.tag }}</a></span>
            <!-- TODO: set proper href to category sub/unsub -->
        </span>
    {% endfor %}
    </div>
{% endblock %}