PBLExchangeDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView 

urlpatterns = [
    url(r'^stud/', RedirectView.as_view(url='http://stud.pblexchange.aau.dk/')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^pble_questions/', include('pble_questions.urls', namespace='pble_questions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_users/', include('pble_users.urls', namespace='pble_users'), {'base_template': 'pblexchange/base.html'}),
    url(r'^pble_subscriptions/', include('pble_subscriptions.urls', namespace='pble_subscriptions'), {'base_template': 'pblexchange/base.html'}),
    url(r'^', include('pblexchange.urls')),
]

pble_questions/urls.py
from django.conf.urls import url, include
from . import views
from .models import Answer, Comment, AnswerVote, CommentVote
from .forms import AnswerForm, CommentForm


urlpatterns = [
    url(r'^search', views.search, name='search'),
    url(r'^new$', views.new, name='new'),
    url(r'^unanswered$', views.unanswered, name='unanswered'),
    url(r'^hot$', views.hot, name='hot'),
    url(r'^bounties$', views.bounties, name='bounties'),
    url(r'^detail/(?P<question_id>[0-9]+)$', views.detail, name='detail'),
    url(r'^tags$', views.tags, name='tags'),
    url(r'^tags/(?P<tag_text>[a-zA-Z0-9_\-]+)$', views.tag, name='tag'),
    url(r'^categories$', views.categories, name='categories'),
    url(r'^categories/(?P<category_id>[0-9]+)$', views.category, name='category'),
    url(r'^ask', views.ask, name='ask'),
    url(r'^submit$', views.submit, name='submit'),
    url(r'^edit/(?P<post_type>[a-z]+)/(?P<post_id>[0-9]+)$', views.edit, name='edit'),
    url(r'^edit_submit/(?P<post_type>[a-z]+)/(?P<post_id>[0-9]+)$', views.edit_submit, name='edit_submit'),
    url(r'^upvote/(?P<post_id>[0-9]+)$', views.vote, {'amount': 1}, name='upvote'),
    url(r'^downvote/(?P<post_id>[0-9]+)$', views.vote, {'amount': -1}, name='downvote'),

    # Post types
    url(r'^answers/', include('pble_questions.answer_urls', namespace='answers'), {
        'post_type': Answer,
        'form_type': AnswerForm,
        'vote_type': AnswerVote,
    }),
    url(r'^comments/', include('pble_questions.comment_urls', namespace='comments'), {
        'post_type': Comment,
        'form_type': CommentForm,
        'vote_type': CommentVote,
    })
]

pble_users/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from . import views
from pble_questions.models import Question, Post
from PBLExchangeDjango.settings import PBLE_GROUPS


detail_patterns = [
    url(r'^$', views.detail, name='detail'),
    url(r'^pble_questions$', views.question_list, {
        'questions': Question.objects.by_user,
        'title_prefix': _('Questions by '),
    }, name='pble_questions'),
    url(r'^unanswered$', views.question_list, {
        'questions': Question.objects.unanswered_by_user,
        'title_prefix': _('Unanswered questions by '),
    }, name='unanswered'),
    url(r'^answers$', views.question_list, {
        'questions': Question.objects.answered_by_user,
        'title_prefix': _('Answers by '),
    }, name='answered'),
    url(r'^bonus_points$', views.bonus_points, name='bonus_points')
]


urlpatterns = [
    url(r'^$', views.users, name='overview'),
    url(r'^detail/(?P<user_id>[0-9]+)/', include(detail_patterns)),
    url(r'^language/(?P<lang_code>[a-zA-Z\-]+)$', views.set_language, name='set_language'),
]

pble_questions/forms.py
import re

from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Question, Answer, Comment, Tag, Category, Post
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class PostEditForm(forms.ModelForm):
    prefix = 'edit'

    class Meta:
        model = Post
        fields = [
            'body',
        ]


class QuestionForm(forms.ModelForm):
    # TODO: Formatting of forms is best handled in CSS
    tags = forms.CharField(required=False, widget=forms.TextInput(attrs={'size': 40}),
                           help_text=_('Tags are comma separated<br><br>'))
    challenge = forms.IntegerField(min_value=0, initial=0)
    prefix = 'question'

    class Meta:
        model = Question
        fields = [
            'title',
            'category',
            'body',
            'bounty',
            'challenge',
            'anonymous',
            'tags',
        ]
        widgets = {'title': forms.TextInput(attrs={'size': 80})}
        # TODO: Formatting of forms is best handled in CSS

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if Category.objects.count() < 1:
            del self.fields['category']
        else:
            self.fields['category'].empty_label = None

    def clean_tags(self):
        # Removes all spaces in the string (tags cannot contain spaces),
        # replace æøå with normal letters, and splits on ','
        tag_strings = re.sub(r'(?![-,])\W', '', re.sub('[\s+]', '', self.cleaned_data['tags']).lower()
                             .replace('æ', 'ae').replace('ø', 'oe').replace('å', 'aa')).split(',')
        tags = []
        for t in tag_strings:
            if t == '':
                continue
            tag, _ = Tag.objects.get_or_create(tag=t)
            tags.append(tag)
        return tags


class AnswerForm(forms.ModelForm):
    body = forms.CharField(label=_('Answer'), widget=CKEditorUploadingWidget())
    prefix = 'answer'

    class Meta:
        model = Answer
        fields = [
            'body',
            'anonymous'
        ]


class CommentForm(forms.ModelForm):
    body = forms.CharField(label=_('Comment'), widget=None)
    prefix = 'comment'

    class Meta:
        model = Comment
        fields = [
            'body',
            'anonymous'
        ]


class SearchForm(forms.Form):
    q = forms.CharField()

    class Meta:
        fields = [
            'q'
        ]

pble_questions/views.py
from django.db.models import Count
from django.shortcuts import render, HttpResponseRedirect, Http404, reverse, get_object_or_404
from django.utils.translation import ugettext as _
from pble_questions.forms import QuestionForm, AnswerForm, CommentForm, SearchForm, PostEditForm
from pble_questions.models import Question, Answer, QuestionVote, Tag, Category, Comment
from PBLExchangeDjango import settings
from pble_users.points import post_vote, answer_accept, post_bounty
from pble_users.models import UserProfile


# Create your views here.
def new(request, base_template='pblexchange/base.html', **kwargs):
    return render(request, 'questions/list.html', {
        'base_template': base_template,
        'title': _('new'),
        'questions': Question.objects.recent(),
    })


def unanswered(request, base_template='pblexchange/base.html', **kwargs):
    return render(request, 'questions/list.html', {
        'base_template': base_template,
        'title': _('unanswered'),
        'questions': Question.objects.unanswered(),
    })


def hot(request, base_template='pblexchange/base.html', **kwargs):
    return render(request, 'questions/list.html', {
        'base_template': base_template,
        'title': _('popular'),
        'questions': Question.objects.hot(),
    })


def bounties(request, base_template='pblexchange/base.html', **kwargs):
    return render(request, 'questions/list.html', {
        'base_template': base_template,
        'title': _('bounty questions'),
        'questions': Question.objects.filter(bounty__gt=0).order_by('-created_date'),
    })


def detail(request, question_id, base_template='pblexchange/base.html', **kwargs):
    question = Question.objects.get(pk=question_id)
    if not question:
        return Http404()
    return render(request, 'questions/detail.html', {
        'base_template': base_template,
        'question': question,
        'answer_form': AnswerForm(),
        'comment_form': CommentForm(),
    })


def ask(request, base_template='pblexchange/base.html', **kwargs):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('login'))
    form = QuestionForm()
    user_up = UserProfile.objects.get(user=request.user)
    if request.user.userprofile.challenge_points < 1:
        del form.fields['challenge']
    return render(request, 'questions/ask.html', {
        'base_template': base_template,
        'post_form': form,
        'current_user_points': user_up.points,
        'current_user_ch_points': user_up.challenge_points
    })


def edit(request, post_type, post_id, base_template='pblexchange/base.html', *args, **kwargs):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('login'))
    try:
        post_t = {
            'question': Question,
            'answer': Answer,
            'comment': Comment,
        }[post_type]
    except LookupError:
        return Http404()

    post = get_object_or_404(post_t, pk=post_id)
    if request.user != post.author:
        return Http404()
    form = PostEditForm(instance=post)
    return render(request, 'questions/edit.html', {
        'base_template': base_template,
        'post_form': form,
        'post_type': post_type,
        'post_id': post.pk,
    })


def edit_submit(request, post_type, post_id, *args, **kwargs):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('login'))
    if request.method != 'POST':
        return Http404()
    try:
        post_t = {
            'question': Question,
            'answer': Answer,
            'comment': Comment,
        }[post_type]
    except LookupError:
        return Http404()

    post = get_object_or_404(post_t, id=post_id)
    if request.user != post.author:
        return Http404()
    form = PostEditForm(request.POST)
    if form.is_valid():
        post.body = form.cleaned_data['body']
        post.save()
    else:
        return Http404()  # TODO Use better error message
    question_id = post.pk if isinstance(post, Question) else post.question.pk
    return HttpResponseRedirect(reverse('pble_questions:detail', args=(question_id,)))


def submit(request, question_id=None, answer_id=None, form_type=QuestionForm, **kwargs):
    if request.method == 'POST' and request.user.is_authenticated():
        post_form = form_type(request.POST)
        if request.user.userprofile.challenge_points < 1 and isinstance(post_form, QuestionForm):
            del post_form.fields['challenge']
        post = post_form.save(commit=False)
        post.author = request.user
        is_question = True
        if question_id:
            question = get_object_or_404(Question, pk=question_id)
            post.question = question
            if answer_id:
                answer = get_object_or_404(Answer, pk=answer_id)
                post.answer = answer
            is_question = False
        if is_question and 'pble_users' in settings.INSTALLED_APPS:
            post_bounty(
                request.user,
                post,
                post_form.cleaned_data['bounty'],
                post_form.cleaned_data['challenge'] if request.user.userprofile.challenge_points > 0 else 0
            )
        post.save()
        post_form.save_m2m()  # needed to save many-to-many relations.
        if is_question:
            return HttpResponseRedirect(reverse('home'))
        else:
            return HttpResponseRedirect(reverse('pble_questions:detail', args=(post.question.pk,)))
    else:
        return Http404()


def vote(request, post_id, amount, post_type=Question, vote_type=QuestionVote, **kwargs):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('login'))
    post = get_object_or_404(post_type, pk=post_id)
    prev_vote = vote_type.objects.filter(post=post.pk, user=request.user)

    if not prev_vote or prev_vote.first().vote != amount:
        if 'pble_users' in settings.INSTALLED_APPS:
            post_vote(request.user, post, vote_type, amount)
        else:
            raise Http404("'pble_users' module does not exist under INSTALLED_APPS in settings.py")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def accept_answer(request, post_id, **kwargs):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('login'))
    post = get_object_or_404(Answer, pk=post_id)

    if not Answer.objects.accepted(post.question) or (Answer.objects.accepted(post.question) and post.accepted):
        if 'pble_users' in settings.INSTALLED_APPS:
            # Assign points and set post.accepted
            answer_accept(request.user, post)
        else:
            raise Http404("'pble_users' module does not exist under INSTALLED_APPS in settings.py")

        post.accepted = not post.accepted
        post.save()

    return HttpResponseRedirect(reverse('pble_questions:detail', args=(post.question.pk,)))


def tags(request, base_template='pblexchange/base.html', **kwargs):
    return render(request, 'questions/tags.html', {
        'base_template': base_template,
        'tags': Tag.objects.annotate(cardinality=Count('question')).order_by('-cardinality'),
    })


def tag(request, tag_text, base_template='pblexchange/base.html', **kwargs):
    t = get_object_or_404(Tag, tag=tag_text)
    return render(request, 'questions/questions.html', {
        'base_template': base_template,
        'title': tag_text,
        'questions': t.question_set.order_by('-created_date'),
    })


def categories(request, base_template='pblexchange/base.html', **kwargs):
    return render(request, 'questions/categories.html', {
        'base_template': base_template,
        'title': _('Categories'),
        'categories': Category.objects.all(),
    })


def category(request, category_id, base_template='pblexchange/base.html', **kwargs):
    cat = get_object_or_404(Category, id=category_id)
    return render(request, 'questions/category.html', {
        'base_template': base_template,
        'title': cat.user_get_i18n_name(request.user),
        'questions': cat.question_set.order_by('-created_date'),
    })


def search(request, base_template='pblexchange/base.html', **kwargs):
    query = SearchForm(request.GET)
    if query.is_valid():
        q = query.cleaned_data['q']
    else:
        q = ''
    questions = Question.objects.query(q)
    return render(request, 'questions/search.html', {
        'base_template': base_template,
        'questions': questions,
    })

pble_questions/templates/questions/answer_notification.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2>Hello {{ recipient_username }},</h2>
        <h3>
            {{ answer_author }} has provided the following answer to your question <a href="{{ q_url }}">{{ q_title }}</a>
        </h3>
        Answer: {{ answer_text }}
    </body>
</html>

pble_questions/templates/questions/ask.html
{% extends base_template %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <h1>{% trans 'Ask a question' %}</h1>
    <form method="POST" action="{% url 'pble_questions:submit' %}" class="pure-form pure-form-stacked">
        {% csrf_token %}
        {{ post_form.media }}
        <p>{% trans 'Title' %}:</p>
        {{ post_form.title }}
        <p>{% trans 'Category' %}:</p>
        {{ post_form.category }}
        <p>{% trans 'Body' %}:</p>
        {{ post_form.body }}
        <p>{% trans 'Bounty' %}: <small>({% trans 'You have' %} {{ current_user_points }} {% trans 'bounty points available' %})</small></p>
        {{ post_form.bounty }}
        {% if current_user_ch_points > 0 %}
        <p>{% trans 'Challenge points' %}: <small>({% trans 'You have' %} {{ current_user_ch_points }} {% trans 'challenge points available' %})</small></p>
        {{ post_form.challenge }}
        {% endif %}
        <p>{% trans 'Anonymous' %}:</p>
        {{ post_form.anonymous }}
        <p>{% trans 'Tags' %}: <small>({% trans 'Tags are separated by commas, and joined using hyphen' %})</small></p>
        {{ post_form.tags }}
        <input type="submit" value="{% trans 'Submit' %}">
    </form>
{% endblock %}

pble_questions/templates/questions/base.html
{% extends base_template %}
{% load i18n %}

{% block sub_menu %}
    <ul class="pble-nav-sub-list">
        <li class="pble-nav-sub-item"><a href="{% url 'pble_questions:new' %}" class="pble-nav-sub-link">{% trans 'Recent' %}</a></li>
        <li class="pble-nav-sub-item pble-nav-sub-hot"><a href="{% url 'pble_questions:hot' %}" class="pble-nav-sub-link">{% trans 'Popular' %}!</a></li>
        <li class="pble-nav-sub-item"><a href="{% url 'pble_questions:unanswered' %}" class="pble-nav-sub-link">{% trans 'Unanswered' %}</a></li>
        <li class="pble-nav-sub-item"><a href="{% url 'pble_questions:bounties' %}" class="pble-nav-sub-link">{% trans 'Unclaimed bounties' %}</a></li>
    </ul>
{% endblock %}

pble_questions/templates/questions/categories.html
{% extends base_template %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Categories' %}</h1>
{% endblock %}

pble_questions/templates/questions/category.html
{% extends base_template %}
{% load questions %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Recent questions posted in' %} {{ title }}</h1>
    {% question_list questions %}
{% endblock %}

pble_questions/templates/questions/detail.html
{% extends base_template %}
{% load questions %}
{% load users %}
{% load i18n %}

{% block content %}
    <h1>{{ question.title }}
        {% if question.bounty > 0 %}
            <span class="pble-bounty">
                +{{ question.bounty }}
            </span>
        {% endif %}
    </h1>
    <div class="pble-part-q-view">
        <div class="pble-q-view hentry question">
            <div class="pble-q-view-stats">
                {% voting question %}
            </div>
            <div class="pble-q-view-main">
                <div class="pble-q-view-content">
                    {{ question.body|safe }}
                </div>
                {% tag_list question 'pble-q-view' %}
                {% post_meta question 'pble-q-view' %}

                {% if question.comment_set.count %}
                <div class="pble-q-view-c-list">
                    {% comment_list question %}
                </div>
                {% endif %}

                <div class="pble-q-view-buttons">
                    {% if request.user == question.author %}
                    <a href="{% url 'pble_questions:edit' 'question' question.pk %}" class="pble-form-light-button pble-form-light-button-edit" style="text-decoration: none; color: inherit;">{% trans 'Edit' %}</a>
                    {% endif %}
                    <label for="comment-q" class="pble-form-light-button pble-form-light-button-comment">{% trans 'Add comment' %}</label>
                    <input type="checkbox" id="comment-q" class="add-comment">
                    <div class="comment-form pble-c-form" {# style="display: none;" #}>
                        <h2>{% trans 'Your comment on this question' %}:</h2>
                        <form action="{% url 'pble_questions:comments:submit:q' question.pk %}" method="post" class="pure-form pure-form-stacked">
                            {% csrf_token %}
                            {{ comment_form.media }}
                            {{ comment_form }}
                            <br/>
                            <button type="submit" class="pure-button pure-button-primary">{% trans 'Submit' %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pble-part-a-list">
        <h2 id="a_list_title">{{ question.answer_set.count }} {% trans 'Answers' %}</h2>
        <div class="pble-a-list" id="a_list">
            {% answer_list question %}
        </div>
        <hr/>

        {% if user.is_authenticated %}
            <form action="{% url 'pble_questions:answers:submit' question.pk %}" method="post" class="pure-form pure-form-stacked">
                {% csrf_token %}
                {{ answer_form.media }}
                {{ answer_form }}
                <br/>
                <button type="submit" class="pure-button pure-button-primary">{% trans 'Submit' %}</button>
            </form>
        {% else %}
            <p>{% trans 'Please' %} <a href="{% url 'login' %}">{% trans 'log in' %}</a> {% trans 'to answer questions' %}.</p>
        {% endif %}
    </div>

{% endblock %}

pble_questions/templates/questions/edit.html
{% extends base_template %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'edit' %}</h1>
    <form method="POST" action="{% url 'pble_questions:edit_submit' post_type post_id %}" class="pure-form pure-form-stacked">
        {% csrf_token %}
        {{ post_form.media }}
        {{ post_form.as_p }}
        <input type="submit" value="{% trans 'Update' %}">
    </form>
{% endblock %}

pble_questions/templates/questions/list.html
{% extends 'questions/base.html' %}
{% load questions %}

{% block content %}
    <h1>{{ title|title }}:</h1>
    {% question_list questions %}
{% endblock %}

pble_questions/templates/questions/questions.html
{% extends base_template %}
{% load questions %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Recent questions tagged' %} {{ title }}</h1>
    {% question_list questions %}
{% endblock %}

pble_questions/templates/questions/search.html
{% extends base_template %}
{% load questions %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Results of search' %}:</h1>
    {% question_list questions %}
{% endblock %}

pble_questions/templates/questions/tags.html
{% extends base_template %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Tags' %}:</h1>
    <div class="pble-part-ranking">
    {% for tag in tags %}
        <span class="pble-ranking-item pble-top-tags-item">
            <span class="pble-top-tags-count">{{ tag.question_set.count }} &#215;</span>
            <span class="pble-top-tags-label"><a href="{% url 'pble_questions:tag' tag.tag %}" class="pble-tag-link">{{ tag.tag }}</a></span>
        </span>
    {% endfor %}
    </div>
{% endblock %}